### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by thm-unix** [saravanabalagi/wmctrl#1]
Hello. Put [https://specifications.freedesktop.org/wm-spec/latest/](https://specifications.freedesktop.org/wm-spec/latest/) instead of [http://www.freedesktop.org/standards/wm-spec](http://www.freedesktop.org/standards/wm-spec) in **EWMH Specification** link.

**Comment by myrdd** [comment]
or this one, with the whole spec in one page  
https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html

**Comment by saravanabalagi** [comment]
Thanks! It's updated now.
